[project]
name = "thesauroor"
version = "0.1.0"
description = "Thesaurus + Tharoor"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.18.0",
    "openai>=1.84.0",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
